- name: install httpd
  yum: name=httpd state=latest
- name: install configuration for httpd
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  tags: 
    - conf
  notify: 
    - restarted httpd
- name: started httpd
  service: name=httpd state=started
